steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/collection-agency-dev-repo/collection-agency-dev-api:$SHORT_SHA',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/collection-agency-dev-repo/collection-agency-dev-api:$SHORT_SHA'
      ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'collection-agency-dev-api',
        '--image',
        'us-central1-docker.pkg.dev/$PROJECT_ID/collection-agency-dev-repo/collection-agency-dev-api:$SHORT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]
