apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: collection-agency-dev
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "1"
        run.googleapis.com/cpu: "500m"
        run.googleapis.com/memory: "256Mi"
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/$PROJECT_ID/collection-agency-dev-repo/collection-agency-dev-api:$SHORT_SHA        
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: DJANGO_SECRET_KEY
                  key: latest
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: DB_HOST
                  key: latest
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: DB_PORT
                  key: latest
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: DB_NAME
                  key: latest
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: DB_USER
                  key: latest
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: DB_PASSWORD
                  key: latest
