services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_db
    networks:
      - backend

  web:
    build: .
    # command: ["gunicorn", "collectionagency.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=myapp_db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - backend

  redis:
    image: redis:alpine
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
