# Generated by Django 5.2 on 2025-04-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["agency"], name="accounts_cl_agency__9e635a_idx"),
        ),
        migrations.AddIndex(
            model_name="collectionagency",
            index=models.Index(fields=["name"], name="accounts_co_name_174dbb_idx"),
        ),
        migrations.AddIndex(
            model_name="consumer",
            index=models.Index(fields=["name"], name="accounts_co_name_461d0c_idx"),
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(fields=["balance"], name="accounts_de_balance_b71c51_idx"),
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(fields=["status"], name="accounts_de_status_2f1d54_idx"),
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(
                fields=["client_reference_no"], name="accounts_de_client__387b53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(fields=["created_at"], name="accounts_de_created_4df51d_idx"),
        ),
    ]
