name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # 3. auth
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. Set up Google Cloud
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # 4. Build the Docker image
      - name: Build Docker image
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/collection-agency-dev-repo/collection-agency-dev --quiet
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      # 5. Deploy the Docker image to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy collection-agency-dev \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/collection-agency-dev-repo/collection-agency-dev \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --add-cloudsql-instances=collection-agency-dev:us-central1:collectionagency-db \
            --service-account=github-actions-sa@collection-agency-dev.iam.gserviceaccount.com
